version: "3.7"
services:
  shinyapp:
    build:
      context: ../.
      dockerfile: ./Docker/shiny/shiny.Dockerfile
    container_name: test_shinyapp1
    image: test_shinyapp1
    expose:
      - 3838
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: ./nginx/nginx.Dockerfile
    container_name: test_shinyapp1_nginx
    image: test_shinyapp1_nginx
    ports:
      - "3838:80"
    depends_on:
      - shinyapp
    restart: unless-stopped
